name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, '-') }}

      - name: Merge dev -> main if dev is ahead
        shell: bash
        run: |
          set -e
          git fetch origin dev main

          AHEAD=$(git rev-list --left-right --count origin/main...origin/dev | awk '{print $2}')
          echo "dev ahead by $AHEAD commits"

          if [ "$AHEAD" = "0" ]; then
            echo "::notice::No diff between dev and main. Skipping merge."
            exit 0
          fi

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout -B main origin/main
          git merge --no-ff --no-edit origin/dev
          git push origin main
