name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure tag is on dev branch
        run: |
          TAG_SHA="${GITHUB_SHA}"
          if ! git branch -r --contains "$TAG_SHA" | grep -q "origin/dev"; then
            echo "❌ Tag commit is not on dev. Aborting."
            exit 1
          fi

      - name: Merge dev -> main
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin dev main
          git checkout -B dev origin/dev
          git checkout -B main origin/main

          git checkout main
          # dev의 변경을 main에 병합 (필요시 --ff-only로 바꿔도 됨)
          git merge --no-ff --no-edit dev

          git push origin main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
