name: Sync main with dev (manual)

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Merge dev -> main if dev is ahead
        shell: bash
        run: |
          set -e
          git fetch origin dev main
          ahead=$(git rev-list --left-right --count origin/main...origin/dev | awk '{print $2}')
          echo "dev ahead by $ahead commits"
          if [ "$ahead" = "0" ]; then
            echo "No diff; done."
            exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B main origin/main
          git merge --no-ff --no-edit origin/dev
          git push origin main
