name: Sync main with dev (manual)

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout (full history)'
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: 'Merge dev -> main (handles unrelated histories)'
        shell: bash
        run: |
          set -e
          git fetch origin dev main

          AHEAD=$(git rev-list --left-right --count origin/main...origin/dev | awk '{print $2}')
          echo "dev ahead by $AHEAD commits"

          if [ "$AHEAD" = "0" ]; then
            echo "::notice::No diff; nothing to sync."
            exit 0
          fi

          BASE=$(git merge-base origin/main origin/dev || true)
          if [ -z "$BASE" ]; then
            echo "::warning::No common history. One-time stitch: set main = dev (force-with-lease)."
            git push origin origin/dev:refs/heads/main --force-with-lease
            exit 0
          fi

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B main origin/main || git checkout main
          git merge --no-ff --no-edit origin/dev
          git push origin main
